/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krimsonkourses.platform;

import com.krimsonkourses.platform.exceptions.ExitApplicationException;
import com.krimsonkourses.platform.exceptions.InvalidRequestException;
import com.krimsonkourses.platform.services.Service;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        String request;
        boolean running = true;
        Service service = new Service();
        while(running) {
            request = scanner.nextLine();
            try {
                System.out.println(service.request(request));
            } catch (InvalidRequestException e) {
                System.out.println(e.getMessage());
            } catch (ExitApplicationException e) {
                System.out.println(e.getExitMessage());
                running = false;
            }
        }
    }
}
